drop table books;
drop table customers;
drop table orders;


CREATE TABLE Books (
    Book_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR2(100),
    Author VARCHAR2(100),
    Genre VARCHAR2(50),
    Published_Year NUMBER,
    Price NUMBER(10,2),
    Stock NUMBER
);

CREATE TABLE Customers (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100),
    Email VARCHAR2(100),
    Phone VARCHAR2(15),
    City VARCHAR2(50),
    Country VARCHAR2(150)
);

CREATE TABLE Orders (
    Order_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Customer_ID NUMBER,
    Book_ID NUMBER,
    Order_Date DATE,
    Quantity NUMBER,
    Total_Amount NUMBER(10,2),
    CONSTRAINT fk_customer FOREIGN KEY (Customer_ID)
        REFERENCES Customers(Customer_ID),
    CONSTRAINT fk_book FOREIGN KEY (Book_ID)
        REFERENCES Books(Book_ID)
); 

Select * from books;
Select * from Customers;
Select * from orders;


-- 1) Retrieve all books in the "Fiction" genre:
Select * from books where genre = 'Fiction';


-- 2) Find books published after the year 1950:
SELECT * FROM books where published_year > '1950';


-- 3) List all customers from the Canada:
Select * from customers where country = 'Canada';

-- 4) Show orders placed in November 2023:
Select * from orders where order_date between '01-NOV-2023' AND '30-NOV-2023';


-- 5) Retrieve the total stock of books available:
Select Sum(stock) as total_stocks from books;

-- 6) Find the details of the most expensive book:
SELECT *
FROM Books
WHERE Price = (
    SELECT MAX(Price)
    FROM Books
);

Select * from 
(Select b.*, dense_rank() over(order by price desc) as dense_rnk from books b) 
where dense_rnk = 1;

-- 7) Show all customers who ordered more than 1 quantity of a book:
Select c.*
from customers c join orders o on c.customer_id = o.customer_id where quantity > 1;

-- 8) Retrieve all orders where the total amount exceeds $20:
Select * from orders where total_amount > 20 order by total_amount;

-- 9) List all genres available in the Books table:
Select distinct genre from books;


-- 10) Find the book with the lowest stock:
Select * from 
(Select b.*, dense_rank() over(order by stock) as dense_rnk from books b) 
where dense_rnk = 1;


-- 11) Calculate the total revenue generated from all orders:
select sum(Total_Amount) as Reveneue from orders;

------------------------------------
-- Advance Questions : 

-- 1) Retrieve the total number of books sold for each genre:
select sum(quantity) as total_books_sold, genre
from books b join orders o on b.book_id = o.book_id group by genre;

-- 2) Find the average price of books in the "Fantasy" genre:
select round(avg(price),2) as average_price from books where genre = 'Fantasy';

-- 3) List customers who have placed at least 2 orders:
SELECT o.customer_id, c.name, COUNT(o.Order_id) AS ORDER_COUNT
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY o.customer_id, c.name
HAVING COUNT(Order_id) >=2;

-- 4) Find the most frequently ordered book:
select o.book_id, b.title, count(order_id) as frequently_ordered_books
from books b 
join orders o on b.book_id = o.book_id 
group by o.book_id, b.title
order by frequently_ordered_books desc
fetch first 1 row with ties;


-- 5) Show the top 3 most expensive books of 'Fantasy' Genre :
Select * from 
(Select b.*, dense_rank() over(partition by genre order by price desc) as dense_rnk from books b) 
where genre = 'Fantasy' and dense_rnk <= 3;

SELECT * FROM books
WHERE genre ='Fantasy'
ORDER BY price DESC
fetch first 3 row with ties;


-- 6) Retrieve the total quantity of books sold by each author:
Select author, sum(quantity) as total_quantity_of_books 
from books b join orders o 
on b.book_id = o.book_id 
group by author;

-- 7) List the cities where customers who spent over $30 are located:
select city
from customers c join orders o on c.customer_id = o.customer_id 
where total_amount > 30;

-- 8) Find the customer who spent the most on orders:
select c.customer_id, sum(total_amount) as amt_spent, c.name
from customers c join orders o on c.customer_id = o.customer_id 
group by c.customer_id, c.name
order by amt_spent;

--9) Calculate the stock remaining after fulfilling all orders:
SELECT b.book_id, b.title, b.stock, COALESCE(SUM(o.quantity),0) AS Order_quantity,  
	b.stock-COALESCE(SUM(o.quantity),0) AS Remaining_Quantity
FROM books b
LEFT JOIN orders o ON b.book_id=o.book_id
GROUP BY b.book_id, b.title, b.stock ORDER BY b.book_id;


--10) Find books that were never ordered
select b.book_id, b.title
from books b left join orders o 
on b.book_id = o.book_id 
where order_id is null;